import { MembershipApplicationItem, ApplicationStatsData } from '../types/membershipApplications.types';

export const INITIAL_APPLICATION_STATS: ApplicationStatsData = {
  total: 612,
  underReview: 124,
  approved: 342,
  rejected: 54,
};

export const INITIAL_APPLICATIONS: MembershipApplicationItem[] = [
  {
    id: 'app-1',
    applicationId: 'APP20260915001',
    applicantName: 'Aman Shaikh',
    membershipType: 'Individual Membership',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'under_review',
    submittedAt: '15 Sep 2026, 11:30 AM',
    submittedDate: '2026-09-15T11:30:00Z',
    phone: '+91 98765 43210',
    email: 'aman@gmail.com',
    gender: 'Male',
    dob: '12 Jan 1996',
    fatherName: 'Salim Shaikh',
    address: 'A-304, Kurla West, Mumbai, Maharashtra 400070',
    occupation: 'Business',
    documents: [
      {
        id: 'doc-1',
        title: 'Aadhaar Card',
        fileName: 'aadhaar_card.pdf',
        fileSize: '251 KB',
        uploadDate: '14/09/26',
      },
      {
        id: 'doc-2',
        title: 'Voter ID',
        fileName: 'voter_id.jpg',
        fileSize: '320 KB',
        uploadDate: '14/09/26',
      },
      {
        id: 'doc-3',
        title: 'Other Document (Employment ID)',
        fileName: 'employee_id.pdf',
        fileSize: '180 KB',
        uploadDate: '14/09/26',
      },
    ],
    activityLog: [
      {
        id: 'log-1',
        title: 'Application Submitted',
        description: 'Application submitted successfully.',
        timestamp: '15 Sep 2026, 11:30 AM',
        status: 'submitted',
      },
      {
        id: 'log-2',
        title: 'Under Review',
        description: 'Application is under review by admin.',
        timestamp: '15 Sep 2026, 01:45 PM',
        status: 'under_review',
      },
      {
        id: 'log-3',
        title: 'Approved',
        description: 'Application approved successfully.',
        timestamp: '16 Sep 2026, 10:20 AM',
        status: 'approved',
      },
    ],
  },
  {
    id: 'app-2',
    applicationId: 'APP20260914023',
    applicantName: 'Saniya Khan',
    membershipType: 'Individual Membership',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'under_review',
    submittedAt: '14 Sep 2026, 04:15 PM',
    submittedDate: '2026-09-14T16:15:00Z',
    phone: '+91 98201 23456',
    email: 'saniya.khan@example.com',
    gender: 'Female',
    dob: '24 Aug 1996',
    fatherName: 'Tariq Khan',
    address: 'B-12, Palm Grove Society, Bandra, Mumbai, MH 400050',
    occupation: 'Teacher',
    documents: [
      {
        id: 'doc-1',
        title: 'Aadhaar Card',
        fileName: 'Aadhaar_SaniyaKhan.pdf',
        fileSize: '1.8 MB',
        uploadDate: '14 Sep 2026',
      },
    ],
    activityLog: [
      {
        id: 'log-1',
        title: 'Under Review',
        description: 'Application received and queued for review.',
        timestamp: '14 Sep 2026, 04:30 PM',
        status: 'under_review',
      },
      {
        id: 'log-2',
        title: 'Application Submitted',
        description: 'Application submitted online via registration portal.',
        timestamp: '14 Sep 2026, 04:15 PM',
        status: 'submitted',
      },
    ],
  },
  {
    id: 'app-3',
    applicationId: 'APP20260913012',
    applicantName: 'Rohit Verma',
    membershipType: 'Individual Membership',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'approved',
    submittedAt: '13 Sep 2026, 10:20 AM',
    submittedDate: '2026-09-13T10:20:00Z',
    phone: '+91 97112 33445',
    email: 'rohit.verma@example.com',
    gender: 'Male',
    dob: '05 Nov 1991',
    fatherName: 'Suresh Verma',
    address: 'House 88, Sector 15, Rohini, New Delhi, DL 110085',
    occupation: 'Business Owner',
    documents: [
      {
        id: 'doc-1',
        title: 'Voter ID',
        fileName: 'VoterID_RohitVerma.pdf',
        fileSize: '1.5 MB',
        uploadDate: '13 Sep 2026',
      },
    ],
    activityLog: [
      {
        id: 'log-1',
        title: 'Application Approved',
        description: 'Identity and credentials verified successfully.',
        timestamp: '14 Sep 2026, 11:00 AM',
        status: 'approved',
      },
      {
        id: 'log-2',
        title: 'Application Submitted',
        description: 'Application submitted online.',
        timestamp: '13 Sep 2026, 10:20 AM',
        status: 'submitted',
      },
    ],
  },
  {
    id: 'app-4',
    applicationId: 'APP20260912008',
    applicantName: 'Faiza Ansari',
    membershipType: 'Individual Membership',
    avatarUrl: undefined,
    status: 'rejected',
    submittedAt: '12 Sep 2026, 02:40 PM',
    submittedDate: '2026-09-12T14:40:00Z',
    phone: '+91 96543 88776',
    email: 'faiza.ansari@example.com',
    gender: 'Female',
    dob: '18 Jul 1998',
    fatherName: 'Akhtar Ansari',
    address: 'Flat 101, Noor Heights, Lucknow, UP 226001',
    occupation: 'Graphic Designer',
    documents: [
      {
        id: 'doc-1',
        title: 'Passport',
        fileName: 'Passport_FaizaAnsari.pdf',
        fileSize: '3.2 MB',
        uploadDate: '12 Sep 2026',
      },
    ],
    activityLog: [
      {
        id: 'log-1',
        title: 'Application Rejected',
        description: 'Submitted identification document was unreadable.',
        timestamp: '13 Sep 2026, 09:15 AM',
        status: 'rejected',
      },
      {
        id: 'log-2',
        title: 'Application Submitted',
        description: 'Application submitted online.',
        timestamp: '12 Sep 2026, 02:40 PM',
        status: 'submitted',
      },
    ],
  },
  {
    id: 'app-5',
    applicationId: 'APP20260911045',
    applicantName: 'Neha Kapoor',
    membershipType: 'Individual Membership',
    avatarUrl: undefined,
    status: 'under_review',
    submittedAt: '11 Sep 2026, 12:10 PM',
    submittedDate: '2026-09-11T12:10:00Z',
    phone: '+91 99887 66554',
    email: 'neha.kapoor@example.com',
    gender: 'Female',
    dob: '30 Jan 1995',
    fatherName: 'Vijay Kapoor',
    address: 'C-45, Vasant Vihar, New Delhi, DL 110057',
    occupation: 'Social Worker',
    documents: [
      {
        id: 'doc-1',
        title: 'Aadhaar Card',
        fileName: 'Aadhaar_NehaKapoor.pdf',
        fileSize: '2.0 MB',
        uploadDate: '11 Sep 2026',
      },
    ],
    activityLog: [
      {
        id: 'log-1',
        title: 'Under Review',
        description: 'Application awaiting document verification.',
        timestamp: '11 Sep 2026, 01:00 PM',
        status: 'under_review',
      },
      {
        id: 'log-2',
        title: 'Application Submitted',
        description: 'Application submitted online.',
        timestamp: '11 Sep 2026, 12:10 PM',
        status: 'submitted',
      },
    ],
  },
  {
    id: 'app-6',
    applicationId: 'APP20260910033',
    applicantName: 'Karan Mehta',
    membershipType: 'Individual Membership',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    status: 'approved',
    submittedAt: '10 Sep 2026, 09:05 AM',
    submittedDate: '2026-09-10T09:05:00Z',
    phone: '+91 91234 56789',
    email: 'karan.mehta@example.com',
    gender: 'Male',
    dob: '14 Oct 1992',
    fatherName: 'Prakash Mehta',
    address: '702, Silver Oak Towers, Ahmedabad, GJ 380015',
    occupation: 'Chartered Accountant',
    documents: [
      {
        id: 'doc-1',
        title: 'Driving Licence',
        fileName: 'DL_KaranMehta.pdf',
        fileSize: '1.6 MB',
        uploadDate: '10 Sep 2026',
      },
    ],
    activityLog: [
      {
        id: 'log-1',
        title: 'Application Approved',
        description: 'All documents verified and approved.',
        timestamp: '11 Sep 2026, 10:00 AM',
        status: 'approved',
      },
      {
        id: 'log-2',
        title: 'Application Submitted',
        description: 'Application submitted online.',
        timestamp: '10 Sep 2026, 09:05 AM',
        status: 'submitted',
      },
    ],
  },
];
